import pdfkit from "pdfkit";
import fs from "fs";


export const createPDF = (document)=>{
    const pdfFile= new pdfkit();

    pdfFile.pipe(fs.createWriteStream('output.pdf'));
    //File creators metaDetails
    let metaDetails = "This document was automatically generated by a scrap bot created by KudahShambare. For more projects by the creator, visit: \n https://github.com/KudahShambare";
    
    pdfFile.fontSize(15).text(metaDetails,{paragraphGap:35,align:"center"}).fontSize(13);
    
    
    //HEADING
    pdfFile.fontSize(20).text(fileHead,{paragraphGap:35,align:"center"}).fontSize(13);
    
    //PARAGRAPHS
    a.map((para)=>{
        return 	pdfFile.text(para,{paragraphGap:30})
    })
    
    pdfFile.end();


    return pdfFile;

}

