
import fetch from "node-fetch";
import cheerio from "cheerio";
import express from "express";
import path from "path";
import bodyParser from "body-parser";
import pdfkit from "pdfkit";
import fs from "fs";

const app=express();

app.use(bodyParser.urlencoded({ extended: false }))
app.use(bodyParser.json())

//use path to access fies
const __dirname=path.resolve();

app.use(express.static("frontend"));


app.post("/url",(req,resp)=>{

	const url=req.body.url;

	const scrap= async()=>{
	try{
		const feching =await fetch(url);
		const body = await feching.text();
		
	const cheerioLoad = await cheerio.load(body);
	const heading=cheerioLoad("h1").text(); //scrap all h1 headings on the site
const result = cheerioLoad("p").text(); //scrap all paragraphs ont he site

//console.log(result);

const paragraphs =result.split("\n"); //put all the paragraphs into an array

const blogArr = [heading,...paragraphs] //add the heasding and the paragraphs into 1 array

return blogArr;


}
catch(err){
	console.error(err)
}
}
let p= scrap(); //returns a promise which has to be resolved by the then function
p.then((a)=>{
	

	const fileHead=a[0];  // first h1 which in most cases the heading of the blog


	a.pop(); // remove last paragraph which usually has blog meta details


	const pdfFile= new pdfkit();

	pdfFile.pipe(fs.createWriteStream('output.pdf'));
//File creators details
	let details = "This document was automatically generated by a scrap bot created by KudahShambare. For more projects by the creator, visit: \n https://github.com/KudahShambare";

	pdfFile.fontSize(15).text(details,{paragraphGap:35,align:"center"}).fontSize(13);


//HEADING
	pdfFile.fontSize(20).text(fileHead,{paragraphGap:35,align:"center"}).fontSize(13);

	//PARAGRAPHS
	a.map((para)=>{
		return 	pdfFile.text(para,{paragraphGap:30})
	})

pdfFile.end();

	resp.set({
		"Content-Type":"applicatio/pdf",
		"Content-Disposition":"attachment/output.pdf"
	}).redirect("/get-file")

})



})

app.get("/get-file",(req,resp)=>{
	resp.sendFile(__dirname+"/output.pdf")
})

const PORT = 5500;
app.listen(PORT,()=>{
	console.log("App listening to port "+PORT);
})

//webpage 



//sortable plainrowheaders wikitable jquery-tablesorter

