[build]
  publish = "frontend"  # This folder contains your static files
  functions = "functions"  # This is where your serverless functions are located

[dev]
  framework = "#custom"
  command = "node functions/index.cjs"
  targetPort = 3000
  port = 8888
  autoLaunch = false
